src/buffer/buffer_pool_manager.cpp
src/include/buffer/buffer_pool_manager.h

The code duplication makes me sad, but I'm not seeing a clean way of wrapping this without macro magic.

Reintroduce buffer pool manager callbacks for grading purposes.

---

test/buffer/clock_replacer_test.cpp

My bad, I thought we could not merge until status checks passed. We should probably switch that on.

Format clock_replacer_test

---

.circleci/config.yml
CMakeLists.txt

Add the CircleCI config file

---

src/include/type/limits.h

Favor constexpr over const

---

src/include/common/config.h
src/include/common/logger.h
src/include/storage/page/table_page.h
src/include/type/limits.h

Convert #define to constexpr

---

src/container/hash/linear_probe_hash_table.cpp
src/include/common/config.h
src/include/container/hash/hash_table.h
src/include/container/hash/linear_probe_hash_table.h
src/include/storage/index/linear_probe_hash_table_index.h
src/include/storage/page/hash_table_block_page.h
src/include/storage/page/hash_table_header_page.h
src/include/storage/page/hash_table_page_defs.h
src/storage/index/linear_probe_hash_table_index.cpp
src/storage/page/hash_table_block_page.cpp
src/storage/page/hash_table_header_page.cpp
test/container/hash_table_page_test.cpp

- Adding `lsn_` field to `hash_table_header_page.h`
- Replace `INDEX_TEMPLATE_ARGUMENTS` with actual templated typenames
- Define `slot_offset_t`

Project 2 Style Changes

---

src/include/storage/page/hash_table_block_page.h
src/include/storage/page/hash_table_header_page.h
src/include/storage/page/hash_table_page_defs.h
src/storage/page/hash_table_block_page.cpp
test/container/hash_table_page_test.cpp

- Change type of `lsn_` in `hash_table_header_page.h`
- Update `hash_table_page_test.cpp` to use GetData()

Project 2 Amendment

---

test/buffer/buffer_pool_manager_test.cpp

Minor fix in buffer pool manager test

---

src/include/recovery/log_record.h
src/storage/page/table_page.cpp

Page id should be initialized in the constructor for NEWPAGE type.

Initialize page_id in constructor for NEWPAGE LogRecord.

---

src/include/primer/p0_starter.h
test/primer/starter_test.cpp

Adding bustub namespace to P0 files.

---

src/include/storage/page/b_plus_tree_leaf_page.h
src/storage/page/b_plus_tree_leaf_page.cpp

Fixed leaf page `Lookup` signature.

Fixed leaf page Lookup signature

---

src/catalog/table_generator.cpp
src/include/catalog/catalog.h
src/include/execution/plans/nested_index_join_plan.h
test/execution/executor_test.cpp

*** Index join plan change ***
&& Minor fix

Project 3 Update

---

.circleci/config.yml

CircleCI Fixes

---

test/primer/starter_test.cpp

a pull request for issue [#144](https://github.com/cmu-db/bustub/issues/114).

Use "std::move" instead of "move" in starter_test.cpp.

---

src/execution/executor_factory.cpp

fix comment

---

src/include/concurrency/transaction.h

Fix AppendIndexWriteRecord API naming

---

src/include/storage/index/b_plus_tree.h
src/storage/index/b_plus_tree.cpp

If it's an empty tree, we can give some DEBUG hints and return.

Add empty check in BPlusTree Print and Draw funcs

---

.clang-tidy
src/storage/index/b_plus_tree.cpp
test/container/hash_table_page_test.cpp
test/recovery/recovery_test.cpp
test/storage/b_plus_tree_concurrent_test.cpp
test/storage/b_plus_tree_delete_test.cpp
test/storage/b_plus_tree_insert_test.cpp
test/storage/b_plus_tree_print_test.cpp

A previous PR made most of the compliance changes for this rule, but this one completes things!

Comply with clang-tidy's modernize use-auto rule.

---

README.md

docs: mark untested build env as not recommended

---

README.md

docs: only sync master to fork

---

.github/workflows/cmake.yml
CMakeLists.txt
test/CMakeLists.txt

close https://github.com/cmu-db/bustub/issues/190

chore(build): warn on non clang-12 compilers

---

src/buffer/CMakeLists.txt
src/buffer/buffer_pool_manager_instance.cpp
src/buffer/lru_k_replacer.cpp
src/common/bustub_instance.cpp
src/include/buffer/buffer_pool_manager_instance.h
src/include/buffer/lru_k_replacer.h
src/include/common/config.h
test/buffer/buffer_pool_manager_instance_test.cpp
test/buffer/mock_buffer_pool_manager.h

- add lru-k replacer starter code
- update buffer pool manager to use the lru-k replacer
- sync [mock_buffer_pool_manager.h](https://github.com/cmu-db/bustub/compare/p1-lruk-starter-and-update-bpm?expand=1#diff-f300cb88f3bf9877606b0d1bc729782841e278e4169edb23195aace6bfd914d7) from private

p1: add lru-k replacer starter code, update bpm to use lru-k replacer

---

src/binder/binder.cpp
src/binder/statement/select_statement.cpp
src/catalog/column.cpp
src/catalog/schema.cpp
src/common/bustub_instance.cpp
src/execution/fmt_impl.cpp
src/include/binder/bound_expression.h
src/include/binder/bound_table_ref.h
src/include/binder/expressions/bound_column_ref.h
src/include/binder/table_ref/bound_join_ref.h
src/include/catalog/column.h
src/include/catalog/schema.h
src/include/common/enums/statement_type.h
src/include/execution/expressions/abstract_expression.h
src/include/execution/expressions/column_value_expression.h
src/include/execution/expressions/comparison_expression.h
src/include/execution/plans/abstract_plan.h
src/include/execution/plans/aggregation_plan.h
src/include/execution/plans/filter_plan.h
src/include/execution/plans/nested_loop_join_plan.h
src/include/planner/planner.h
src/planner/planner.cpp
tools/shell/shell.cpp

PTAL if you're interested and if you have time :) Comments welcomed @TennyZhuang @leiysky

feat(planner): plan join

---

src/common/bustub_instance.cpp
src/execution/CMakeLists.txt
src/execution/executor_factory.cpp
src/execution/mock_scan_executor.cpp
src/include/catalog/catalog.h
src/include/common/bustub_instance.h
src/include/execution/executors/mock_scan_executor.h
src/include/execution/plans/abstract_plan.h
src/include/execution/plans/mock_scan_plan.h
src/include/planner/planner.h
src/planner/planner.cpp
test/binder/binder_test.cpp
tools/shell/shell.cpp

Plan MockScan so that students can run simple queries before they actually implement a buffer pool.

feat(planner): plan and execute mock scan

---

src/include/common/rwlatch.h

Fewer bugs, more happiness. Merge after p0 so that students won't be affected by this change.

chore(common): use shared_mutex for rwlatch

---

.gitignore
CMakeLists.txt

* p1: check-clang-tidy-p1, submit-p1

p1: check-clang-tidy-p1, submit-p1 (#332)

---

third_party/CMakeLists.txt
third_party/linenoise/.gitignore
third_party/linenoise/CMakeLists.txt
third_party/linenoise/LICENSE
third_party/linenoise/README.markdown
third_party/linenoise/example.c
third_party/linenoise/linenoise.c
third_party/linenoise/linenoise.h
third_party/versions.txt
tools/shell/CMakeLists.txt
tools/shell/shell.cpp

For reviewers: please rebase and merge.
This PR adds linenoise, which makes shell experience better.

feat(shell): record history and support arrow keys

---

src/CMakeLists.txt
src/common/bustub_instance.cpp
src/include/optimizer/optimizer.h
src/optimizer/CMakeLists.txt
src/optimizer/optimizer.cpp
src/planner/planner.cpp

After a second thought, I think it would be a better idea to do something in a separate phase instead of in planner. Examples:
* Select index for join
* Select join algorithm (rewrite NLJ to HashJoin)
* Filter push-down
* ...

feat(optimizer): add noop optimizer

---

src/common/bustub_instance.cpp
src/execution/values_executor.cpp
src/include/execution/executors/values_executor.h
src/include/execution/plans/values_plan.h
src/include/planner/planner.h
src/planner/CMakeLists.txt
src/planner/plan_insert.cpp
src/planner/planner.cpp

feat(planner): plan insert

---

src/execution/fmt_impl.cpp
src/execution/values_executor.cpp
src/include/execution/plans/abstract_plan.h
src/include/execution/plans/insert_plan.h
src/include/planner/planner.h
src/planner/CMakeLists.txt
src/planner/plan_aggregation.cpp
src/planner/planner.cpp

As title, we can plan `group by` now.
Having is not support for now. Select group by column is not supported for now (we can only select aggregation functions).

feat(planner): plan hash agg

---

src/buffer/buffer_pool_manager_instance.cpp

chore(bpm): throw when unimplemented

---

CMakeLists.txt
src/catalog/table_generator.cpp
src/include/binder/bound_table_ref.h
src/include/common/macros.h
src/include/common/util/hash_util.h
src/include/execution/expressions/column_value_expression.h
src/include/storage/disk/disk_manager.h
src/include/storage/disk/disk_manager_memory.h
src/storage/disk/CMakeLists.txt
src/storage/disk/disk_manager_memory.cpp
src/storage/page/table_page.cpp
test/table/tuple_test.cpp

fix: release mode build

---

build_support/run_clang_format.py

fix(build): exit code 1 if clang-format fails

---

src/include/buffer/lru_k_replacer.h

p1: update lru-k replacer evict description

---

src/include/execution/expressions/abstract_expression.h
src/include/execution/expressions/column_value_expression.h
src/include/execution/expressions/comparison_expression.h
src/include/execution/expressions/constant_value_expression.h
src/include/execution/plans/abstract_plan.h
src/include/execution/plans/aggregation_plan.h
src/include/execution/plans/delete_plan.h
src/include/execution/plans/filter_plan.h
src/include/execution/plans/hash_join_plan.h
src/include/execution/plans/index_scan_plan.h
src/include/execution/plans/insert_plan.h
src/include/execution/plans/limit_plan.h
src/include/execution/plans/mock_scan_plan.h
src/include/execution/plans/nested_index_join_plan.h
src/include/execution/plans/nested_loop_join_plan.h
src/include/execution/plans/projection_plan.h
src/include/execution/plans/seq_scan_plan.h
src/include/execution/plans/sort_plan.h
src/include/execution/plans/topn_plan.h
src/include/execution/plans/update_plan.h
src/include/execution/plans/values_plan.h
src/include/optimizer/optimizer.h
src/optimizer/CMakeLists.txt
src/optimizer/merge_filter_nlj.cpp
src/optimizer/merge_projection.cpp
src/optimizer/nlj_as_hash_join.cpp
src/optimizer/optimizer.cpp

close https://github.com/cmu-db/bustub/issues/367

feat(optimizer): merge filter into NLJ and optimize NLJ into hash join

---

.gitignore
src/binder/bind_select.cpp
src/include/execution/plans/delete_plan.h
src/include/execution/plans/insert_plan.h
src/include/execution/plans/update_plan.h
src/planner/plan_insert.cpp

close https://github.com/cmu-db/bustub/issues/375

fix(planner): check insert schema match

---

src/include/buffer/buffer_pool_manager_instance.h

chore(p1): update comments for FlushPgImp

---

src/include/buffer/lru_k_replacer.h

Signed-off-by: xinchengxx <2240131203@qq.com>
just fix the typo

fix(typo): fix the typo

---

.clang-tidy
src/binder/bind_insert.cpp
src/binder/bind_select.cpp
src/binder/statement/insert_statement.cpp
src/common/bustub_instance.cpp
src/include/binder/statement/insert_statement.h
src/include/binder/table_ref/bound_base_table_ref.h
src/include/catalog/catalog.h
src/include/catalog/schema.h
src/include/execution/plans/delete_plan.h
src/include/execution/plans/index_scan_plan.h
src/include/execution/plans/sort_plan.h
src/include/optimizer/optimizer.h
src/include/planner/planner.h
src/include/storage/index/b_plus_tree_index.h
src/include/storage/index/index.h
src/optimizer/CMakeLists.txt
src/optimizer/merge_filter_nlj.cpp
src/optimizer/merge_projection.cpp
src/optimizer/nlj_as_hash_join.cpp
src/optimizer/optimizer.cpp
src/optimizer/order_by_index_scan.cpp
src/planner/plan_insert.cpp
src/planner/planner.cpp

* Some refactors on binder, now we bind full table info for insert
* Support create index statement
* Support plan delete
* Fix some bugs in optimizer
* Support plan order by index column as index scan

feat(optimizer): plan order by as index scan, support create index

---

src/common/bustub_instance.cpp
tools/shell/shell.cpp

close https://github.com/cmu-db/bustub/issues/363
close https://github.com/cmu-db/bustub/issues/331
```
bustub> create table t1(v1 int, v2 int, v3 int);
Table created with id = 3
bustub> create index t1v1 on t1(v1);
Index created with id = 0
bustub> \d t1
name=t1 oid=3
v1:INTEGER
v2:INTEGER
v3:INTEGER
index_name=t1v1 oid=0
v1:INTEGER
bustub> 
```

feat(cli): show table info and create sample table

---

CMakeLists.txt
src/binder/bind_select.cpp
src/binder/statement/explain_statement.cpp
src/common/bustub_instance.cpp
src/execution/fmt_impl.cpp
src/execution/values_executor.cpp
src/include/binder/statement/explain_statement.h
src/include/execution/executors/values_executor.h
src/include/execution/plans/abstract_plan.h
src/include/execution/plans/aggregation_plan.h
src/optimizer/merge_projection.cpp
src/planner/plan_aggregation.cpp
src/planner/plan_select.cpp
test/sql/baby_arithmetic.slt
test/sql/hash_join.slt
test/sql/nested_index_join.slt
test/sql/order_by.slt
test/sql/subquery.slt
third_party/linenoise/linenoise.c
tools/CMakeLists.txt
tools/shell/shell.cpp
tools/wasm-shell/CMakeLists.txt
tools/wasm-shell/index.html
tools/wasm-shell/wasm-shell.cpp

This PR adds WASM shell, and fix several bugs / add several improvements in the system.
* Explain support options (show only binder / planner / optimizer result)
* values executor should set cursor to 0 when init
* merge projection rule is wrong
close https://github.com/cmu-db/bustub/issues/382
close https://github.com/cmu-db/bustub/issues/371

feat(build): add web shell

---

test/CMakeLists.txt

chore(build): test timeout 1min

---

src/storage/index/b_plus_tree.cpp
tools/b_plus_tree_printer/b_plus_tree_printer.cpp

fix(tools): flush when draw to file, stop when cin is invalid

---

src/execution/fmt_impl.cpp
src/include/execution/plans/limit_plan.h
src/include/execution/plans/topn_plan.h
src/include/optimizer/optimizer.h
src/optimizer/CMakeLists.txt
src/optimizer/optimizer.cpp
src/optimizer/sort_limit_as_topn.cpp

feat(p3): Add top N and optimizer rule  

---

src/binder/CMakeLists.txt
src/binder/bind_variable.cpp
src/binder/statement/index_statement.cpp
src/binder/transformer.cpp
src/common/bustub_instance.cpp
src/include/binder/binder.h
src/include/binder/statement/set_show_statement.h
src/include/common/bustub_instance.h
src/include/common/enums/statement_type.h
src/include/optimizer/optimizer.h
src/optimizer/CMakeLists.txt
src/optimizer/optimizer.cpp
src/optimizer/optimizer_custom_rules.cpp
test/sql/p3.04-index-scan.slt
tools/sqllogictest/parser.cpp
tools/sqllogictest/parser.h
tools/sqllogictest/sqllogictest.cpp

feat(binder,sqllogictest): support extra options

---

build_support/build-web-shell.sh
tools/wasm-bpt-printer/extra_files/index.html
tools/wasm-shell/extra_files/index.html
tools/wasm-shell/extra_files/vercel.json

chore(build): use relative path for shell

---

src/include/binder/table_ref/bound_join_ref.h
src/include/execution/plans/hash_join_plan.h
src/include/execution/plans/nested_index_join_plan.h
src/include/execution/plans/nested_loop_join_plan.h
src/optimizer/merge_filter_nlj.cpp
src/optimizer/nlj_as_hash_join.cpp
src/optimizer/nlj_as_index_join.cpp
src/planner/plan_table_ref.cpp
src/storage/table/tuple.cpp

This PR supports left-join for nested loop join, nested index join, and hash join. It also fixes some memory issues for null values in the `Tuple` type.

feat(executor): support left joins, fix tuple bug

---

tools/sqllogictest/sqllogictest.cpp

feat(sqllogictest): support check index scan / topn

---

CMakeLists.txt
src/common/bustub_instance.cpp
src/execution/filter_executor.cpp
src/execution/hash_join_executor.cpp
src/execution/nested_index_join_executor.cpp
src/execution/nested_loop_join_executor.cpp
src/optimizer/optimizer_custom_rules.cpp
test/sql/p3.16-integration-2.slt

feat(p3): add submission command

---

src/execution/mock_scan_executor.cpp
src/include/common/bustub_instance.h
src/include/execution/executors/mock_scan_executor.h
src/include/optimizer/optimizer.h
src/optimizer/optimizer.cpp
test/sql/p3.00-primer.slt
test/sql/p3.10-multi-way-join.slt
test/sql/p3.leaderboard-q1.slt
test/sql/p3.leaderboard-q2.slt
test/sql/p3.leaderboard-q3.slt
tools/sqllogictest/sqllogictest.cpp

feat(p3): add leaderboard tests

---

src/include/execution/executors/aggregation_executor.h

Fix SimpleAggregationHashTable functions and add TODO

---

CMakeLists.txt
test/sql/p3.10-multi-way-join.slt

fix(p3): add topn rule to submit list

---

CMakeLists.txt
test/CMakeLists.txt
test/sql/p3.07-group-agg-1.slt
test/sql/p3.09-simple-join.slt
test/sql/p3.10-multi-way-join.slt
test/sql/p3.14-topn.slt
test/sql/p3.16-integration-2.slt
tools/sqllogictest/sqllogictest.cpp

feat(p3): finalize tests

---

src/include/execution/executors/delete_executor.h
src/include/execution/executors/filter_executor.h
src/include/execution/executors/hash_join_executor.h
src/include/execution/executors/insert_executor.h
src/include/execution/executors/nested_index_join_executor.h
src/include/execution/executors/nested_loop_join_executor.h
src/include/execution/executors/update_executor.h
src/include/execution/executors/values_executor.h
src/include/execution/plans/aggregation_plan.h
src/include/execution/plans/index_scan_plan.h
src/include/execution/plans/insert_plan.h
src/include/execution/plans/mock_scan_plan.h
src/include/execution/plans/nested_loop_join_plan.h
src/include/execution/plans/seq_scan_plan.h
src/include/execution/plans/sort_plan.h
src/include/execution/plans/topn_plan.h
src/include/execution/plans/values_plan.h

fix(p3): update comments for project 3

---

src/include/storage/index/stl_comparator_wrapper.h

chore: check-in stl comparator

---

src/common/bustub_instance.cpp
src/include/common/bustub_instance.h
test/concurrency/transaction_test.cpp
test/recovery/recovery_test.cpp

feat(p4,test): bring back p4 tests using new interface

---

src/binder/bind_insert.cpp
src/binder/bind_select.cpp
src/binder/statement/CMakeLists.txt
src/binder/statement/update_statement.cpp
src/binder/transformer.cpp
src/execution/fmt_impl.cpp
src/execution/update_executor.cpp
src/include/binder/binder.h
src/include/binder/statement/delete_statement.h
src/include/binder/statement/index_statement.h
src/include/binder/statement/insert_statement.h
src/include/binder/statement/set_show_statement.h
src/include/binder/statement/update_statement.h
src/include/execution/executors/update_executor.h
src/include/execution/plans/filter_plan.h
src/include/execution/plans/hash_join_plan.h
src/include/execution/plans/nested_loop_join_plan.h
src/include/execution/plans/update_plan.h
src/include/planner/planner.h
src/planner/plan_expression.cpp
src/planner/plan_insert.cpp
src/planner/planner.cpp
test/sql/update.slt

prepare for p4 leaderboard test

feat(planner): plan and execute update

---

test/storage/b_plus_tree_contention_test.cpp

feat(p2): move contention benchmark to public repo

---

src/include/execution/plans/seq_scan_plan.h
src/include/optimizer/optimizer.h
src/optimizer/CMakeLists.txt
src/optimizer/eliminate_true_filter.cpp
src/optimizer/merge_filter_scan.cpp

prepare for p4 for students to implement index point get scan / optimize range lock

feat(optimizer): add merge filter scan rule

---

src/include/execution/plans/aggregation_plan.h
src/include/execution/plans/delete_plan.h
src/include/execution/plans/hash_join_plan.h
src/include/execution/plans/index_scan_plan.h
src/include/execution/plans/insert_plan.h
src/include/execution/plans/limit_plan.h
src/include/execution/plans/nested_index_join_plan.h
src/include/execution/plans/projection_plan.h
src/include/execution/plans/sort_plan.h
src/include/execution/plans/topn_plan.h
src/include/execution/plans/values_plan.h

So as to make life easier for optimizer hackers :)

chore(p3): make fields of plan node public

---

src/include/optimizer/optimizer.h
src/optimizer/eliminate_true_filter.cpp
src/optimizer/merge_filter_scan.cpp

Remove this after p3 deadline and before p4 🤣

fix: allow old copy of optimizer

---

.gitattributes
src/include/catalog/column.h
src/optimizer/optimizer.cpp
tools/sqllogictest/parser.cpp

fix(p3): accept CRLF for sqllogictest, fix optimizer

---

CMakeLists.txt
src/concurrency/lock_manager.cpp
src/include/concurrency/lock_manager.h
src/include/concurrency/transaction.h
src/include/concurrency/transaction_manager.h
src/storage/page/table_page.cpp
src/storage/table/table_heap.cpp
test/concurrency/deadlock_detection_test.cpp
test/concurrency/lock_manager_test.cpp
test/concurrency/transaction_test.cpp

feat(p4): concurrency control

---

src/CMakeLists.txt

Linked Theads to bustub

---

src/include/storage/disk/disk_manager_memory.h

fix(disk_manager): allow read out of range

---

src/include/primer/p0_trie.h

Fix some typos and grammar errors

fix typos and grammar errors

---

src/binder/bind_select.cpp

fix(binder): correctly bind and/or

---

src/include/concurrency/lock_manager.h

fix(p4): IS -> IX

---

src/storage/index/b_plus_tree.cpp

Just stumbled upon these typos while doing project 2 (B+ tree index).

fix(typos): b_plus_tree.cpp routine descriptions

---

.github/workflows/cmake.yml
CMakeLists.txt
build_support/packages.sh
src/container/hash/extendible_hash_table.cpp
src/include/container/hash/extendible_hash_table.h

feat(build): bump to llvm 14

---

CMakeLists.txt

chore(build): allow no sanitize for build

---

test/primer/trie_debug_test.cpp

fix(p0): hide answer in stdout

---

src/include/primer/trie.h

The property will be useful when removing a node. If the node doesn't have children BUT has a value inside, we cannot remove it.

fix(p0): add is_value_node property

---

test/storage/page_guard_test.cpp

fix: remove check GetData in test case

---

src/include/storage/index/b_plus_tree.h
src/include/storage/page/b_plus_tree_header_page.h
src/include/storage/page/b_plus_tree_internal_page.h
src/include/storage/page/b_plus_tree_leaf_page.h
src/include/storage/page/b_plus_tree_page.h
src/storage/index/b_plus_tree.cpp
src/storage/page/b_plus_tree_internal_page.cpp
src/storage/page/b_plus_tree_leaf_page.cpp
src/storage/page/b_plus_tree_page.cpp

also we are dropping parent page id and page id.

chore: rename root page -> header page

---

src/include/common/logger.h

fix the bug of PastLastSlash. #507

fix: PastLastSlash bug

---

src/include/storage/page/b_plus_tree_internal_page.h
src/include/storage/page/b_plus_tree_leaf_page.h
src/storage/page/b_plus_tree_internal_page.cpp
src/storage/page/b_plus_tree_leaf_page.cpp

fix: remove page id / parent id

---

tools/bpm_bench/bpm_bench.cpp

fix(bpm-bench): concurrency issues

---

src/include/storage/index/index_iterator.h

Reverse behavior of `IndexIterator::IsEnd`

---

src/common/bustub_instance.cpp
src/execution/CMakeLists.txt
src/execution/executor_factory.cpp
src/execution/init_check_executor.cpp
src/include/common/bustub_instance.h
src/include/execution/check_options.h
src/include/execution/execution_engine.h
src/include/execution/executor_context.h
src/include/execution/executors/abstract_executor.h
src/include/execution/executors/init_check_executor.h
src/include/execution/plans/abstract_plan.h
src/include/execution/plans/init_check_plan.h
tools/sqllogictest/sqllogictest.cpp

Changes: 
- Added NLJ Init Checker
- Added CheckExecutors to ExecutionContext
- Added CheckOptions for ParseExtraOption

test(p3): add nlj init check

---

.github/workflows/cmake.yml

ci: no fail fast

---

CMakeLists.txt
src/execution/fmt_impl.cpp
src/execution/hash_join_executor.cpp
src/execution/nested_index_join_executor.cpp
src/execution/nested_loop_join_executor.cpp
src/include/execution/plans/hash_join_plan.h
src/include/execution/plans/nested_loop_join_plan.h
src/include/optimizer/optimizer.h
src/include/optimizer/optimizer_internal.h
src/optimizer/CMakeLists.txt
src/optimizer/eliminate_true_filter.cpp
src/optimizer/merge_filter_nlj.cpp
src/optimizer/nlj_as_hash_join.cpp
src/optimizer/nlj_as_index_join.cpp
src/optimizer/optimizer_custom_rules.cpp
src/optimizer/optimizer_internal.cpp

refactor(p3): composite-key hashjoin

---

src/execution/mock_scan_executor.cpp
test/sql/p3.00-primer.slt
test/sql/p3.06-simple-agg.slt
test/sql/p3.07-group-agg-1.slt
test/sql/p3.09-simple-join.slt
test/sql/p3.10-multi-way-join.slt
test/sql/p3.11-repeat-execute.slt
test/sql/p3.13-sort-limit.slt
tools/sqllogictest/sqllogictest.cpp

test(p3): add nlj and hash join checks

---

src/execution/CMakeLists.txt
src/execution/executor_factory.cpp
src/execution/topn_check_executor.cpp
src/execution/topn_executor.cpp
src/include/execution/executors/topn_check_executor.h
src/include/execution/executors/topn_executor.h

test(p3): add topn check

---

CMakeLists.txt
src/include/storage/page/table_page.h
src/include/storage/table/table_heap.h
src/storage/page/table_page.cpp
src/storage/table/table_heap.cpp

fix(p3): add in place update to avoid dead loop

---

src/execution/mock_scan_executor.cpp
test/sql/p3.leaderboard-q1.slt
test/sql/p3.leaderboard-q2.slt
test/sql/p3.leaderboard-q3.slt

feat(p3): new leaderboard q1

---

src/catalog/table_generator.cpp
src/concurrency/lock_manager.cpp
src/include/concurrency/lock_manager.h
src/include/concurrency/transaction.h
src/include/concurrency/transaction_manager.h
src/include/optimizer/optimizer.h
src/include/storage/page/table_page.h
src/include/storage/table/table_heap.h
src/include/storage/table/table_iterator.h
src/optimizer/eliminate_true_filter.cpp
src/optimizer/merge_filter_scan.cpp
src/storage/page/table_page.cpp
src/storage/table/table_heap.cpp
src/storage/table/table_iterator.cpp
test/sql/p3.03-update.slt
test/table/tuple_test.cpp

feat(p4): refactor table heap + tuple for project 4

---

src/execution/init_check_executor.cpp
src/include/execution/execution_engine.h

I haven't tested this in the private repo. Would you please help test + merge + update the grader? Thanks a lot! cc @christopherlim98 @yliang412

fix(p3): nlj check should only consider number of actual tuples

---

tools/terrier_bench/terrier.cpp

fix(p4): default to 10 nfts for terrier bench

---

test/concurrency/lock_manager_test.cpp

The test case is hard to describe verbally by printing in one line, and therefore it might be a good idea to make it public.

chore: add abort test

---

src/include/concurrency/transaction.h

chore: remove unused member in txn

---

src/storage/table/table_heap.cpp
tools/terrier_bench/terrier.cpp

fix: do not allow S/X table lock in bench

---

test/concurrency/lock_manager_test.cpp

chore: more info for lock number incorrect

---

src/storage/index/b_plus_tree.cpp

see [https://stackoverflow.com/a/2783833](https://stackoverflow.com/a/2783833)

fix: InsertFromFile() and RemoveFromFile() read extra value

---

src/include/buffer/buffer_pool_manager.h
src/include/buffer/lru_k_replacer.h
src/include/concurrency/lock_manager.h
src/include/container/disk/hash/disk_extendible_hash_table.h
src/include/execution/executors/aggregation_executor.h
src/include/execution/executors/delete_executor.h
src/include/execution/executors/limit_executor.h
src/include/execution/executors/nested_index_join_executor.h
src/include/execution/executors/nested_loop_join_executor.h
src/include/execution/executors/topn_check_executor.h
src/include/execution/executors/topn_executor.h
src/include/execution/executors/update_executor.h
src/include/execution/plans/abstract_plan.h
src/include/execution/plans/delete_plan.h
src/include/execution/plans/index_scan_plan.h
src/include/execution/plans/insert_plan.h
src/include/execution/plans/nested_index_join_plan.h
src/include/execution/plans/topn_plan.h
src/include/execution/plans/update_plan.h
src/include/primer/trie_store.h
src/include/storage/index/b_plus_tree.h
src/include/storage/index/generic_key.h
src/include/storage/index/index.h
src/include/storage/table/table_heap.h
src/include/storage/table/tuple.h
src/planner/plan_aggregation.cpp
src/planner/plan_func_call.cpp
test/concurrency/lock_manager_test.cpp

This PR mainly does three things in general.
1. According to the unofficial discord conversation history in 2022 P4-2022, 
by `@ moraceae` & `@ chichi` & `@ francischeng`, which indicated it'd be hard to avoid memory leak if using raw pointer instead of smart pointer, and it really is.
Thus, this PR updates the raw pointer inside `LockRequestQueue::request_queue_` to `std::shared_ptr`, which makes life much easier (If by any chance the students just follow this paradigm and structure when programming through `LockManager`..)
3. Also according to the suggestion from `@ moraceae` & `@ chichi`, I updated the [Lock Note] for `lock upgrade` and `book keeping` sections, to give students a hint and also remind the students about the correct logic. (I didn't find any reference about this through …

feat: update LockRequestQueue::request_queue_ & fix typos & ensure format consistency

---

test/primer/trie_test.cpp

Adding missing case where root value is written then removed.
we do have write root check but don't have remove root check. let's make it up.

fix(test): add check in COW test where root value is written then removed

---

src/concurrency/transaction_manager.cpp
src/include/concurrency/transaction.h
src/include/concurrency/transaction_manager.h

This PR improves format and resolves a todo (for `TransactionAbortException`) related to transaction part 🥰

chore(docs): improve overall format & resolve todo related to transaction part

---

test/primer/trie_test.cpp

cherry-pick as the original PR picks the wrong branch to merge

fix(test): add check in COW test where root value is written then removed (#590)

---

test/primer/trie_store_test.cpp

p0: test concurrent put/get in mixed test

---

src/buffer/buffer_pool_manager.cpp
src/include/buffer/buffer_pool_manager.h
src/include/common/channel.h
src/include/storage/disk/disk_scheduler.h
src/storage/disk/CMakeLists.txt
src/storage/disk/disk_scheduler.cpp

Add disk scheduler to P1

---

CMakeLists.txt

2023 p1 config update

---

src/include/buffer/buffer_pool_manager.h
test/storage/disk_scheduler_test.cpp

Add test for DiskScheduler.

---

CMakeLists.txt

p1: remove page guard files from CMake

---

src/include/storage/page/extendible_htable_bucket_page.h
src/storage/page/extendible_htable_bucket_page.cpp
test/storage/extendible_htable_bucket_page_test.cpp

feat: implement extendible htable bucket page helpers

---

src/include/storage/page/extendible_htable_directory_page.h
src/include/storage/page/extendible_htable_header_page.h
src/storage/page/extendible_htable_directory_page.cpp
src/storage/page/extendible_htable_header_page.cpp

feat: implement extendible htable header and directory page helpers

---

src/include/storage/disk/disk_manager_memory.h

p1: check disk scheduler threading

---

tools/bpm_bench/bpm_bench.cpp

p1: disallow nullptr for fetchpage in bench

---

CMakeLists.txt

chore: update p2 submission files

---

src/container/disk/hash/disk_extendible_hash_table_utils.cpp
src/include/container/disk/hash/disk_extendible_hash_table.h
test/container/disk/hash/extendible_htable_concurrent_test.cpp
tools/CMakeLists.txt
tools/htable_bench/CMakeLists.txt
tools/htable_bench/htable_bench.cpp

fest: add more concurrent tests and htable-bench for p2

---

src/include/common/macros.h

fix: show error message for ensure

---

src/common/bustub_instance.cpp
src/execution/fmt_impl.cpp
src/include/common/bustub_instance.h
src/include/execution/plans/window_plan.h

better explain window plan

---

src/binder/bind_create.cpp
src/binder/statement/create_statement.cpp
src/catalog/table_generator.cpp
src/common/bustub_ddl.cpp
src/common/bustub_instance.cpp
src/include/binder/statement/create_statement.h
src/include/catalog/catalog.h
src/include/common/bustub_instance.h
src/include/common/config.h
src/include/concurrency/lock_manager.h
src/include/concurrency/transaction_manager.h
src/include/execution/plans/index_scan_plan.h
src/include/storage/index/index.h
src/include/storage/page/table_page.h
src/include/storage/table/table_heap.h
src/include/storage/table/tuple.h
src/optimizer/order_by_index_scan.cpp
src/storage/table/table_heap.cpp
src/storage/table/tuple.cpp
test/table/tuple_test.cpp

TODO: add DuckDB license and finish float / bool binder support.

add primary key support and change tuple meta format

---

src/planner/plan_window_function.cpp
test/sql/p3.20-window_function.slt

testcase + order_by checks

---

CMakeLists.txt
src/include/concurrency/transaction_manager.h
test/CMakeLists.txt
test/sql/p3.14-hash-join.slt
tools/terrier_bench/terrier.cpp

Fix: update p3 files

---

tools/wasm-shell/extra_files/index.html

bump web-shell version

---

test/sql/p3.20-window-function.slt

Project3: ignore order

---

src/include/storage/index/stl_equal_wrapper.h
src/include/storage/index/stl_hasher_wrapper.h

feat: implement more stl wrappers

---

src/include/catalog/column.h
tools/sqllogictest/sqllogictest.cpp

Update column.h + flush stdout in sqllogictest

---

src/storage/table/table_heap.cpp

fix: MakeIterator takes read latch twice in a thread

---

test/txn/txn_common.h
test/txn/txn_executor_test.cpp
test/txn/txn_index_concurrent_test.cpp
test/txn/txn_index_test.cpp
test/txn/txn_scan_test.cpp

p4: add test cases for task 4

---

src/execution/executor_factory.cpp
src/include/execution/executors/topn_per_group_executor.h

fix: add group topn to executor factory

---

src/concurrency/transaction_manager.cpp
src/concurrency/transaction_manager_impl.cpp
src/include/concurrency/transaction_manager.h
src/include/storage/table/table_heap.h
src/storage/table/table_heap.cpp
test/txn/txn_executor_test.cpp
test/txn/txn_scan_test.cpp
test/txn/txn_timestamp_test.cpp
tools/terrier_bench/terrier.cpp

p4: verify total count for terrier bench + more comments for starter code

---

tools/shell/shell.cpp

fix: bustub shell memory leak

---

src/execution/execution_common.cpp
test/txn/txn_common.h
test/txn/txn_executor_test.cpp
test/txn/txn_scan_test.cpp
tools/terrier_bench/terrier.cpp

p4: add missing test, add hints for dbgtxnmgr

---

src/include/catalog/catalog.h
src/optimizer/optimizer_custom_rules.cpp
src/optimizer/order_by_index_scan.cpp

fix order by index scan rule

---

test/txn/txn_common.h
test/txn/txn_index_concurrent_test.cpp
tools/terrier_bench/terrier.cpp

p4: misc fixes for tests

---

test/txn/txn_scan_test.cpp

p4: fix hidden test case query

---

test/sql/p3.06-empty-table.slt

p3: fix empty table test

---

build_support/packages.sh

Update prompt message as discussed here: https://github.com/cmu-db/bustub/issues/672

update `build_support/packages.sh` prompt message

---

GRADESCOPE.md.template
gradescope_sign.py

Students may use `python3 gradescope_sign.py` to generate a signature and we will verify it on Gradescope.

add request signature script

---

build_support/packages.sh

Resolves https://piazza.com/class/lph5an72faw2s/post/17

fix homebrew install link in setup script

---

src/include/storage/disk/write_back_cache.h
test/storage/write_back_cache_test.cpp

fix header and misleading comments

---

test/sql/p3.05-index-scan.slt

add rowsort option to indexscan test query

update indexscan test

---

tools/terrier_bench/terrier.cpp

Feat: Spring24 project4 update leaderboard metrics

---

test/txn/txn_abort_serializable_test.cpp

Fixing the disability of the test's typo error

Correction of Test Disability typo

---

test/primer/hyperloglog_test.cpp

Changes in Test case

---

src/include/common/config.h
src/include/storage/disk/disk_manager.h
src/include/storage/disk/disk_manager_memory.h
src/include/storage/page/page_guard.h
src/storage/disk/disk_manager.cpp
src/storage/disk/disk_manager_memory.cpp
test/storage/page_guard_test.cpp

This PR simply cleans up a few style things on the backend of public facing code (in order to sync with the private repo). Students should not have modified any of these files, so there shouldn't be any merge conflicts.

clean up public-facing backend code

---

test/buffer/buffer_pool_manager_test.cpp

Fix typos in contention test

---

test/buffer/buffer_pool_manager_test.cpp

Somehow I didn't sync this one test's changes.

Sync `PagePinMediumTest`

---

tools/wasm-bpt-printer/wasm-bpt-printer.cpp

Remove txn for wasm-bpt-printer

---

tools/wasm-bpt-printer/extra_files/index.html

Sync b+tree printer index.html

---

src/execution/mock_scan_executor.cpp

test(f24-p3): modify mock graph table

---

src/include/storage/index/b_plus_tree_debug.h

fix(p2): rid inconsistency in b plus tree printer

---

src/execution/execution_common.cpp
src/include/execution/execution_common.h
test/txn/txn_executor_test.cpp
test/txn/txn_scan_test.cpp

Major change:
Add three helper functions `CollectUndoLogs`, `GenerateNewUndoLog`, and `GenerateUpdatedUndoLog`.
Add test cases in `txn_scan_test` and `txn_executor_test` for these helper functions.

fall 2024 p4 update

---

src/include/primer/hyperloglog.h

Fix typo in hyperloglog.h

---

CMakeLists.txt
tools/wasm-shell/extra_files/index.html

fix: fix web shell OOM issue

---

test/primer/skiplist_test.cpp

test(p0): add more elements into the list increase ConcurrentReadTest runtime

---

src/include/primer/hyperloglog_presto.h

Fix comment spelling in `src/include/primer/hyperloglog_presto.h`

---

test/buffer/buffer_pool_manager_test.cpp

Fix the PagePinEasyTest 
@yliang412

bug(test): fix PagePinEasyTest in buffer pool test

---

CMakeLists.txt
src/include/primer/count_min_sketch.h
src/primer/CMakeLists.txt
src/primer/count_min_sketch.cpp
test/CMakeLists.txt
test/primer/count_min_sketch_test.cpp

This pull request consists of the start code and test suite for Project 0 of 15445/15645 Fall 2025. This project asks students to implement a working [Count-min Sketch](https://en.wikipedia.org/wiki/Count%E2%80%93min_sketch) able to make adequate estimates of item frequency in a data stream. 
It serves to give students an overview of the data structure and test their abilities with navigating code, practicing C++ fundamentals, and handling concurrent operations.

f25-p0: starter code
