- README.md
Added blurb about using build_support/packages.sh to set up packages on Linux/Mac
> Update README w/ Linux/Mac info

- test/buffer/buffer_pool_manager_test.cpp
Some whitespace got into the test file while CI wasn't up and is failing all the builds.
> Fix check-format

- src/common/util/string_util.cpp
- src/include/catalog/column.h
- src/include/storage/disk/disk_manager.h
- src/include/type/integer_parent_type.h
- src/include/type/value_factory.h
- src/storage/page/header_page.cpp
- src/type/timestamp_type.cpp
clang-tidy only checks header files which are actually included and in use.
These files were not caught as part of the initial 5500 or so clang-tidy things because nothing was including them. We now need them for the autograder.
> Fix clang-tidy in header files used for grading

- src/include/catalog/column.h
- src/include/common/config.h
- src/include/type/value_factory.h
- test/buffer/buffer_pool_manager_test.cpp
Google test is a bit of a pain. Even if you delete the disk manager, you'll leak memory. You need both disk manager and buffer pool manager to be pointers to be cleanly deleted.
We already fixed this in the autograder last/lastlast week, but we forgot to port it here. Hopefully the new infrastructure will fix this.
> Fix the memory leak in the sample buffer pool test.

- src/include/catalog/schema.h
Fixes a dumb legacy bug as pointed out by a student, Piazza 460.
> Fix Schema::GetColIdx.

- src/storage/disk/disk_manager.cpp
The buffer_used global variable was initialized outside the constructor. For repeated instantiations of disk manager, as in the logging test cases, it does not get initialized causing `assert(log_data != buffer_used);` in disk_manager.cpp to fail.
This issue could not reproduced locally on Mac but consistently on AWS.
> Initialise global variable in Disk Manager Constructor

- src/storage/table/tuple.cpp
It is unclear why this only has to be done for some submissions; people have obtained full scores without doing this. I suspect this may actually be covering up bugs in student implementations, but without concrete proof of that, this seems like a reasonable thing to be doing. We can revisit this in the winter break cleanup.
> Explicitly zero out the tuple's data on construction.

- build_support/cpplint.py
- src/include/common/bustub_instance.h
The old version complains after format because format wants `auto [a,
b]` while lint think `auto[a, b]` is the right one i.e. no extra space. It is fixed in upstream already https://github.com/google/styleguide/pull/487
NOTE: I am using https://github.com/google/styleguide/tree/gh-pages/cpplint instead of the fork https://github.com/cpplint/cpplint The fix is in both repos and I am not sure the origin of the one in bustub repo, the diff with both repos are pretty large so I picked the google one for now.
> Build: Update cpplint for C++17 tuple destructing

- src/storage/disk/disk_manager.cpp
- test/storage/disk_manager_test.cpp
- The constructor doesn't re-check if `db_io_` or `log_io_` were
successfully re-opened if the file doesn't exist. Checks were
added for this, and we throw if either file fails to `open()`.
- `ReadPage()` tolerates partial reads that terminate prematurely at
EOF, but this will cause the failbit to be set. The error flag is now 
`clear()`'ed when less than a page is read so that subsequent
operations can proceed.
- Like their `Write*()` counterparts, `ReadPage()` and `ReadLog()` should
check error flags after each IO operation, and log errors appropriately.
- To find the filename extension, use `rfind()` to find the last `.` rather
than the first.
- For good measure, add some tests that verify these fixes.
- If the filename lacks a `.`, we log an error and create a useless object. I …
> Fix a few bugs in DiskManager

- src/type/value.cpp
Found an obvious typo while reading the code. If boolean is for real the intended type here, then line 176 should be changed instead
> Fix typo in type.cpp

- src/include/recovery/log_record.h
I found some clear typo in log_record.h. Besides, some of the tuples in the class `LogRecord` are not public yet.
> Fix typo in log_record.h and public several tuples in class LogRecord

- CMakeLists.txt
The deleted cmake code is copied from a low-quality stack overflow
answer [0]. The answer suggests adding a CMAKE_CXX_FLAG in terms of $<,
which is a Makefile-ism. However, CMake is supposed to support other
build system targets such as Ninja. Referring to $< breaks the Ninja
build. It appears that the __BUSTUBFILE__ macro is unused in the code
base anyways so this patch just deletes the unused and buggy CMake code.
If this __BUSTUBFILE__ macro is desired, it should be implemented in
terms of portable CMake code such as in [1] instead.
[0] http://stackoverflow.com/a/16658858
[1] https://stackoverflow.com/questions/1706346/file-macro-manipulation-handling-at-compile-time/27990434#27990434
> Remove nonportable and unused cmake code

- .clang-format
- .clang-tidy
Make clang-format forward compatible with modern clang (>8) by explicitly setting default options which have changed from clang 8 to clang 10.
Disable clang-tidy options added after clang-8. This prevents students using modern clang versions from getting clang-tidy errors. One alternative way to resolve this issue would be to actually make the modern clang-tidy fixes in the current codebase, but this patch solves the issue without causing any code churn.
Let me know if you guys would rather see the clang-tidy issue solved by actually upstreaming the fixes requested by clang-tidy 10.
> Make clang-format and clang-tidy configs forward-compatible for students running modern clang versions (>8)

- README.md
If we build the docker image without specify its name `bustub`, the second instruction `docker create -t -i --name bustub -v $(pwd):/bustub bustub bash` will fail
> Fix README.md for build docker image

- src/include/storage/page/b_plus_tree_internal_page.h
- src/storage/page/b_plus_tree_internal_page.cpp
The middle key is valid in the source page, so it could be copied over without getting the separation middle key from the parent.
> Deleted unnecessary middle_key arguments for the InternalPage  

- CMakeLists.txt
People tend to accidentally run cmake from the wrong folder, which might nuke their source tree and/or cause weird bugs. This forces an out-of-source CMake build by detecting if you are running cmake in a directory that already contains a CMakeLists.txt.
Small snippet extracted from the cmake refactor in NoisePage. You might want this for later projects.
> Add a CMake safeguard to root CMakeLists.txt.

- CMakeLists.txt
> Remove quotes in find_program hints parameter to allow clang-format and clang-tidy to be found

- src/include/storage/page/b_plus_tree_internal_page.h
- src/storage/page/b_plus_tree_internal_page.cpp
`MoveLastToFrontOf` will also need the separating key from the parent.
> Fix signature for checkpoint 2

- src/storage/index/b_plus_tree.cpp
`silbing_page` is not UNPINED after `FetchPage` call, which may cause some problems.
> fix bug in BPLUSTREE_TYPE::ToGraph

- src/include/execution/executors/update_executor.h
- test/execution/executor_test.cpp
This PR makes SimpleRawInsertWithIndexTest explicitly call keyFromTuple to construct index key
> Fix Index Key in Test

- test/recovery/recovery_test.cpp
- test/storage/disk_manager_test.cpp
- Remove test.db and test.log before test run to avoid test
failures caused by non-empty test.db and test.log from
other failed tests.
- Add NOLINTNEXTLINE.
- Use SetUp() and TearDown() methods in RecoveryTest 
and DiskManagerTest.
> Use SetUp() and TearDown() to clean up test.db and test.log

- src/buffer/buffer_pool_manager_instance.cpp
In `BufferPoolManagerInstance::ValidatePageId`, the `page_id` mod `num_instances` with `the instance_index` is assert to be equal, but the `instance_index` is not assigned an initial value in **BPI**, which causes its value to always be 0.
> Fix initialize instance_index_ in BPI

- src/include/storage/index/int_comparator.h
Fixes #184: Prevents overflow in IntComparator and marks operator() as const
> Fix overflow in IntComparator

- src/include/execution/plans/aggregation_plan.h
- test/execution/executor_test.cpp
In the initial release of Project 3, I did not include tests for some executors by design. However, after speaking with students, I have realized that the use of some of the executors (or the construction of their plan nodes) assumes some knowledge about the arguments they expect that may be difficult to determine from comments alone. This PR just adds a few more sample tests for the untested executors.
> Add Sample Tests for Untested Executors

- src/include/common/util/hash_util.h
- src/include/execution/plans/aggregation_plan.h
- test/execution/executor_test.cpp
Clang Tidy identifies uninitialized memory in some calls to `HashUtil::CombineHashes()` despite the fact that the memory is correctly initialized. This PR zero-initializes the stack-allocated array used within `HashUtil::CombineHashes()` to avoid this false-positive.
> Clang Tidy Uninitialized Memory False Positive

- src/storage/page/hash_table_directory_page.cpp
just as the diff shows, the logged variable should be curr_count
> fix log bug in directory page Verify func

- src/storage/index/b_plus_tree.cpp
Let `ToGraph` display the size of b-plus-tree nodes for better debugging.
> feat: add the size of the display b-tree node for the ToGraph method

- src/type/decimal_type.cpp
BUSTUB_INT64_MAX
conversion from 'const int64_t' (aka 'const long') to 'double' changes value from 9223372036854775807 to 9223372036854775808
BUSTUB_INT64_MIN
conversion from 'const int64_t' (aka 'const long') to 'double' changes value from -9223372036854775807 to -9223372036854775808
value  >= static_cast<double>(BUSTUB_INT64_MAX) || value < static_cast<double>(BUSTUB_INT64_MIN)
so the value at this range will throw OUT_OF_RANGE exception
> Fix conversion loss when checking BIGINT bounds in decimal_type.cpp

- src/include/storage/page/b_plus_tree_internal_page.h
- src/include/storage/page/b_plus_tree_leaf_page.h
- src/include/storage/page/hash_table_block_page.h
- src/include/storage/page/hash_table_bucket_page.h
- src/include/storage/page/hash_table_header_page.h
C++ does not support flexible array members. [Here's a good source](http://david.tribble.com/text/cdiffs.htm#C99-fam).
This is only supported by compiler convention.
If you want to abuse C99 things where the C++ compiler plays nice, remove the number altogether i.e. `MappingType array[];`.
Seeing as how this type is always instantiate via a reinterpret cast, this should not be a performance or correctness issue.
The issue with this being undefined behavior is that it may not exist, or may go away if a compiler optimization level deems it to be a candidate for "no-unique-address" behavior.
> Changing compliance for zero-length arrays

- README.md
It was previously pointing to cmu-db/benchbase.
> Fix GH Actions link in README

- .clang-tidy
This PR brings the reference solution into compliance with newer versions of clang-tidy.  Compliance with these rules would only involve changing test names and the random number generation API, so it can be done reasonably quickly in the future.
> Disable 2 clang rules for refsol compliance

- src/include/storage/page/hash_table_bucket_page.h
In #151, comments for flexible array member were added. But the comment was missed in `hash_table_bucket_page.h`, which confuse me a lot.
> Add a comment for  flexible array member

- test/execution/executor_test.cpp
close https://github.com/cmu-db/bustub/issues/260
tested with sample solution, which works fine.
By the way, it seems that all our execution tests' test data are randomly generated (table_generator.cpp), which might make things hard when someone want to debug their code and see what's wrong. I will look into the possibility of having some tables of fixed value in our tests in the future if possible.
> fix(executor): add sum column for test

- src/storage/disk/disk_manager.cpp
close https://github.com/cmu-db/bustub/issues/150
```
log_io_.open(log_name_, std::ios::binary | std::ios::trunc | std::ios::app | std::ios::out);
```
This line will always fail and doesn't take effect at all. We can directly create (or truncate) a file if we can't open it.
> fix(disk_manager): remove redundant open file

- CMakeLists.txt
- src/CMakeLists.txt
- src/buffer/CMakeLists.txt
- src/catalog/CMakeLists.txt
- src/common/CMakeLists.txt
- src/concurrency/CMakeLists.txt
- src/container/CMakeLists.txt
- src/container/hash/CMakeLists.txt
- src/execution/CMakeLists.txt
- src/recovery/CMakeLists.txt
- src/storage/CMakeLists.txt
- src/storage/disk/CMakeLists.txt
- src/storage/index/CMakeLists.txt
- src/storage/page/CMakeLists.txt
- src/storage/table/CMakeLists.txt
- src/type/CMakeLists.txt
- test/CMakeLists.txt
- third_party/CMakeLists.txt
- third_party/murmur3/CMakeLists.txt
This is part of https://github.com/garrisonhess/bustub-public/pull/20, which will eventually make us easier to introduce DuckDB's parser. <del>Still working on integrating it with our ref solutions.</del>
> refactor(build): use separate CMakeLists for each component

- CMakeLists.txt
- build_support/run_clang_tidy.py
close https://github.com/cmu-db/bustub/issues/272
This PR adds a new Makefile command `check-clang-tidy-diff`, which runs clang-tidy only on files diff to origin/master.
> chore: run clang-tidy on git diff

- CMakeLists.txt
- build_support/run_clang_tidy.py
- src/CMakeLists.txt
- src/primer/CMakeLists.txt
- src/primer/p0_trie.cpp
Add a new Makefile entry for checking 2022 Fall's p0. Will check only one file so it's significantly faster. Will use this Makefile entry in gradescope. <del>Can merge before https://github.com/cmu-db/bustub/pull/287.</del>
> feat(build): add check-clang-tidy-p0 for p0

- CMakeLists.txt
Students won't need to remove the build directory, though this is recommended.
> chore(build): discover tools after being installed

- CMakeLists.txt
- README.md
Thread sanitizer can help check potential race conditions. By default, thread sanitizers print warnings. We can modify it to exit with code 1 if any race condition is detected in the future.
Instructions on enabling thread sanitizer is described in readme.
macOS users will need to use AppleClang to build thread sanitizer. So I'm going to change some descriptions in README and cmake build scripts to recommend macOS users to use AppleClang instead of homebrew clang if they want to use thread sanitizer.
close https://github.com/cmu-db/bustub/issues/288
> chore(build): support thread sanitizer

- src/buffer/buffer_pool_manager_instance.cpp
- src/include/buffer/buffer_pool_manager_instance.h
- test/container/hash/extendible_hash_table_test.cpp
- Remove parallel bpm related variables in buffer_pool_manager_instance.h
- Use ExtendibleHashTable as page table in buffer_pool_manager_instance
- Add extendible hash table test
> p1: use extendible hash table in bpm and add starter tests

- src/type/timestamp_type.cpp
timestamp_type.cpp should use snprintf, not sprintf #322. This change allows building on recent versions of MacOS, and should be safer besides.
close #322
> chore(type): use snprintf instead of sprint

- src/binder/statement/select_statement.cpp
- src/include/binder/bound_expression.h
- src/include/binder/bound_table_ref.h
- src/include/binder/statement/select_statement.h
- src/include/binder/table_ref/bound_base_table_ref.h
- src/include/binder/table_ref/bound_cross_product_ref.h
- src/include/binder/table_ref/bound_join_ref.h
- test/CMakeLists.txt
- test/binder/binder_test.cpp
In this PR, we added support for bind `from A inner join B on Condition` and `from A, B where Condition`.
> feat(binder): bind join and cross join

- .gitignore
- src/include/concurrency/transaction.h
- src/include/container/hash/extendible_hash_table.h
- src/include/storage/page/hash_table_page_defs.h
- src/storage/index/b_plus_tree.cpp
- test/CMakeLists.txt
- test/buffer/counter.h
cc @timlee0119 we missed one function from the private repo. Shall we add it to the public header? (They can remove it at any time).
I was scared when I see the header of `src/storage/index/b_plus_tree.cpp`, but it turned out it isn't a private one. So I removed the header.
> refactor: sync from private repo

- src/binder/CMakeLists.txt
- src/binder/bind_insert.cpp
- src/binder/bind_select.cpp
- src/binder/fmt_impl.cpp
- src/binder/statement/insert_statement.cpp
- src/binder/transformer.cpp
- src/common/util/string_util.cpp
- src/execution/fmt_impl.cpp
- src/include/binder/binder.h
- src/include/binder/bound_expression.h
- src/include/binder/bound_table_ref.h
- src/include/binder/statement/insert_statement.h
- src/include/binder/table_ref/bound_expression_list_ref.h
- src/include/common/util/string_util.h
- src/include/execution/plans/values_plan.h
- src/include/planner/planner.h
- src/include/type/value.h
- src/planner/CMakeLists.txt
- src/planner/plan_table_ref.cpp
- src/planner/planner.cpp
- test/binder/binder_test.cpp
* Refactor planner and split `plan_table_ref.cpp` out.
* Plan `values` as `ExpressListTableRef`
* Bind insert.
> feat(binder): bind insert and values

- test/CMakeLists.txt
So that autograder won't have color, but students' console will.
> chore(test): set gtest_color=auto

- src/common/bustub_instance.cpp
- src/include/binder/bound_expression.h
- src/include/binder/expressions/bound_agg_call.h
- src/include/binder/expressions/bound_alias.h
- src/include/binder/expressions/bound_binary_op.h
- src/include/binder/expressions/bound_column_ref.h
- src/include/binder/expressions/bound_constant.h
- src/include/binder/expressions/bound_star.h
- src/include/binder/expressions/bound_unary_op.h
- src/include/binder/tokens.h
- src/include/planner/planner.h
- src/planner/CMakeLists.txt
- src/planner/plan_aggregation.cpp
- src/planner/plan_expression.cpp
- src/planner/plan_insert.cpp
- src/planner/plan_select.cpp
- src/planner/planner.cpp
- tools/shell/shell.cpp
Not tested with refsol yet, but the plan looks correct. See comments in `PlanSelectAgg` for more.
```
bustub> select colB, sum(colA) > max(colB) from __mock_table_1 group by colB having min(colA) == 3;
=== BINDER ===
BoundSelect {
table=BoundBaseTableRef { table=__mock_table_1 },
columns=[__mock_table_1.colB, (sum([__mock_table_1.colA])>max([__mock_table_1.colB]))],
groupBy=[__mock_table_1.colB],
having=(min([__mock_table_1.colA])==3),
where=
}
=== PLANNER ===
Projection { exprs=[#0.0, #0.2>#0.3] } | (__mock_table_1.colB:INTEGER, <unnamed>:BOOLEAN)
Filter { predicate=#0.1=3 } | (__mock_table_1.colB:INTEGER, agg#0:INTEGER, agg#1:INTEGER, agg#2:INTEGER)
Agg { types=[min, sum, max], aggregates=[#0.0, #0.0, #0.1], having=, group_by=[#0.1] } | (__mock_table_1.colB:INTEGER, agg#0:INTEGER, …
```
> feat(planner): plan having and select group by column in hashagg

- src/binder/bind_insert.cpp
- src/binder/bind_select.cpp
- src/binder/statement/CMakeLists.txt
- src/binder/statement/explain_statement.cpp
- src/binder/statement/insert_statement.cpp
- src/binder/statement/select_statement.cpp
- src/binder/transformer.cpp
- src/common/bustub_instance.cpp
- src/execution/filter_executor.cpp
- src/execution/fmt_impl.cpp
- src/include/binder/binder.h
- src/include/binder/bound_order_by.h
- src/include/binder/statement/explain_statement.h
- src/include/binder/statement/select_statement.h
- src/include/execution/executors/filter_executor.h
- src/include/execution/expressions/abstract_expression.h
- src/include/execution/plans/limit_plan.h
- src/include/execution/plans/sort_plan.h
- src/planner/plan_aggregation.cpp
- src/planner/plan_select.cpp
- src/planner/plan_table_ref.cpp
As title.
```
bustub> explain select * from __mock_table_1 order by (colA > colB) desc limit 10;
=== BINDER ===
BoundExplain {
statement=
BoundSelect {
table=BoundBaseTableRef { table=__mock_table_1 },
columns=[__mock_table_1.colA, __mock_table_1.colB],
groupBy=[],
having=,
where=,
limit=10,
offset=,
order_by=[BoundOrderBy { type=Descending, expr=(__mock_table_1.colA>__mock_table_1.colB) }]},
}
=== PLANNER ===
Sort { order_bys=(Descending, #0.0>#0.1) } | (__mock_table_1.colA:INTEGER, __mock_table_1.colB:INTEGER)
Limit { limit=10 } | (__mock_table_1.colA:INTEGER, __mock_table_1.colB:INTEGER)
Projection { exprs=#0.0, #0.1 } | (__mock_table_1.colA:INTEGER, __mock_table_1.colB:INTEGER)
MockScan { size=100 } | (__mock_table_1.colA:INTEGER, __mock_table_1.colB:INTEGER)
=== OPTIMIZER ===
Sort { …
```
> feat(planner): support plan order by, limit, and explain

- src/binder/bind_select.cpp
- src/binder/fmt_impl.cpp
- src/binder/statement/explain_statement.cpp
- src/binder/statement/select_statement.cpp
- src/common/bustub_instance.cpp
- src/common/util/string_util.cpp
- src/include/binder/binder.h
- src/include/binder/bound_table_ref.h
- src/include/binder/expressions/bound_agg_call.h
- src/include/binder/expressions/bound_column_ref.h
- src/include/binder/statement/select_statement.h
- src/include/binder/table_ref/bound_expression_list_ref.h
- src/include/binder/table_ref/bound_subquery_ref.h
- src/include/common/util/string_util.h
- src/include/planner/planner.h
- src/planner/plan_aggregation.cpp
- src/planner/plan_expression.cpp
- src/planner/plan_select.cpp
- src/planner/plan_table_ref.cpp
```
Agg { types=[], aggregates=[], having=, group_by=[#0.0, #0.1] } | (__subquery#1.__subquery#0.__mock_table_1.colA:INTEGER, __subquery#1.maxcolc:INTEGER)
Projection { exprs=#0.0, #0.1 } | (__subquery#1.__subquery#0.__mock_table_1.colA:INTEGER, __subquery#1.maxcolc:INTEGER)
Projection { exprs=#0.0, #0.1 } | (__subquery#1.__subquery#0.__mock_table_1.colA:INTEGER, __subquery#1.maxcolc:INTEGER)
Projection { exprs=#0.0, #0.1 } | (__subquery#0.__mock_table_1.colA:INTEGER, maxcolc:INTEGER)
Agg { types=[max], aggregates=[#0.1], having=, group_by=[#0.0] } | (__subquery#0.__mock_table_1.colA:INTEGER, agg#0:VARCHAR)
Projection { exprs=#0.0, #0.1 } | (__subquery#0.__mock_table_1.colA:INTEGER, __subquery#0.__mock_table_2.colC:VARCHAR)
Projection { …
```
> feat(planner): plan subquery and distinct

- src/execution/plan_node.cpp
- src/include/execution/plans/abstract_plan.h
- src/include/execution/plans/aggregation_plan.h
- src/include/execution/plans/delete_plan.h
- src/include/execution/plans/filter_plan.h
- src/include/execution/plans/hash_join_plan.h
- src/include/execution/plans/index_scan_plan.h
- src/include/execution/plans/insert_plan.h
- src/include/execution/plans/limit_plan.h
- src/include/execution/plans/mock_scan_plan.h
- src/include/execution/plans/nested_index_join_plan.h
- src/include/execution/plans/nested_loop_join_plan.h
- src/include/execution/plans/projection_plan.h
- src/include/execution/plans/seq_scan_plan.h
- src/include/execution/plans/sort_plan.h
- src/include/execution/plans/topn_plan.h
- src/include/execution/plans/update_plan.h
- src/include/execution/plans/values_plan.h
- src/include/optimizer/optimizer.h
- src/optimizer/CMakeLists.txt
- src/optimizer/merge_projection.cpp
- src/optimizer/optimizer.cpp
- src/planner/plan_aggregation.cpp
The smart ptr refactor makes optimizer rules easier to implement. The ProjectionMerge optimizer rule will eliminate unnecessary projections.
```
=== PLANNER ===
Agg { types=[], aggregates=[[]], having=, group_by=[[#0.0, #0.1]] } | (__subquery#1.__subquery#0.__mock_table_1.colA:INTEGER, __subquery#1.maxcolc:INTEGER)
Projection { exprs=[#0.0, #0.1] } | (__subquery#1.__subquery#0.__mock_table_1.colA:INTEGER, __subquery#1.maxcolc:INTEGER)
Projection { exprs=[#0.0, #0.1] } | (__subquery#1.__subquery#0.__mock_table_1.colA:INTEGER, __subquery#1.maxcolc:INTEGER)
Projection { exprs=[#0.0, #0.1] } | (__subquery#0.__mock_table_1.colA:INTEGER, maxcolc:INTEGER)
Agg { types=[max], aggregates=[[#0.1]], having=, group_by=[[#0.0]] } | (__subquery#0.__mock_table_1.colA:INTEGER, agg#0:INTEGER)
Projection { …
```
> feat(optimizer): merge projections

- src/binder/bind_select.cpp
- src/binder/fmt_impl.cpp
- src/execution/plan_node.cpp
- src/include/binder/expressions/bound_column_ref.h
- src/include/binder/table_ref/bound_base_table_ref.h
- src/include/binder/table_ref/bound_subquery_ref.h
- src/include/catalog/schema.h
- src/include/execution/plans/seq_scan_plan.h
- src/planner/plan_expression.cpp
- src/planner/plan_table_ref.cpp
Handling alias is somehow messy in the current implementation. Let's refactor it later.
For now we just use some hacks to support `select * from (select * from t1)`.
close https://github.com/cmu-db/bustub/issues/355
> feat(binder): support select star from subquery

- src/binder/bind_select.cpp
- src/binder/transformer.cpp
- src/include/binder/expressions/bound_agg_call.h
- src/include/common/config.h
- src/include/storage/page/b_plus_tree_internal_page.h
- src/include/storage/page/b_plus_tree_leaf_page.h
- src/include/storage/page/hash_table_page_defs.h
- src/include/storage/page/page.h
- src/storage/disk/disk_manager.cpp
- src/storage/disk/disk_manager_memory.cpp
- src/storage/table/table_heap.cpp
- test/CMakeLists.txt
- test/buffer/buffer_pool_manager_instance_test.cpp
- test/recovery/recovery_test.cpp
- test/storage/disk_manager_test.cpp
- test/storage/tmp_tuple_page_test.cpp
This PR includes changes on some headers. `PAGE_SIZE` is defined in Emscripten, so we rename it to `BUSTUB_PAGE_SIZE`. Also clang-16 detects some issues with missing `std::` before move.
> fix(build): compile to wasm

- src/binder/bind_create.cpp
- src/binder/bind_insert.cpp
- src/binder/bind_select.cpp
- src/binder/statement/CMakeLists.txt
- src/binder/statement/delete_statement.cpp
- src/binder/statement/index_statement.cpp
- src/binder/transformer.cpp
- src/include/binder/binder.h
- src/include/binder/bound_expression.h
- src/include/binder/statement/index_statement.h
- src/include/common/enums/statement_type.h
- src/include/execution/expressions/abstract_expression.h
- src/include/execution/plans/abstract_plan.h
This PR adds support for binding `create index` and `delete from table <where x>`.
close https://github.com/cmu-db/bustub/issues/359
close https://github.com/cmu-db/bustub/issues/362
> feat(binder): bind index and delete

- src/include/execution/expressions/arithmetic_expression.h
- src/include/execution/expressions/comparison_expression.h
- src/include/execution/expressions/logic_expression.h
- src/include/planner/planner.h
- src/planner/plan_expression.cpp
- src/planner/plan_select.cpp
- src/planner/plan_table_ref.cpp
* Support `select 1, 2, 3`.
* Also fixes a bug on subquery, so that we can `select * from (select 1, 2, 3)`.
close https://github.com/cmu-db/bustub/issues/356
close https://github.com/cmu-db/bustub/issues/357
> feat(expr): arithmetic and logic expression

- src/binder/bind_select.cpp
- src/common/bustub_instance.cpp
- src/include/execution/plans/nested_index_join_plan.h
- src/include/execution/plans/seq_scan_plan.h
- src/include/optimizer/optimizer.h
- src/optimizer/CMakeLists.txt
- src/optimizer/nlj_as_index_join.cpp
- src/optimizer/optimizer.cpp
- src/planner/plan_table_ref.cpp
```
bustub> create table t1(v1 int, v2 int);
Table created with id = 3
bustub> create table t2(v3 int, v4 int);
Table created with id = 4
bustub> create index t1v1 on t1(v1);
Index created with id = 0
bustub> explain select * from t2 inner join t1 on v1=v3;
=== BINDER ===
BoundExplain {
statement=BoundSelect {
table=BoundJoin { type=Join, left=BoundBaseTableRef { table=t2, oid=4 }, right=BoundBaseTableRef { table=t1, oid=3 }, condition=(t1.v1=t2.v3) },
columns=[t2.v3, t2.v4, t1.v1, t1.v2],
groupBy=[],
having=,
where=,
limit=,
offset=,
order_by=[],
is_distinct=false,
},
}
=== PLANNER ===
Projection { exprs=[#0.0, #0.1, #0.2, #0.3] } | (t2.v3:INTEGER, t2.v4:INTEGER, t1.v1:INTEGER, t1.v2:INTEGER)
NestedLoopJoin { predicate=#1.0=#0.0 } | (t2.v3:INTEGER, t2.v4:INTEGER, t1.v1:INTEGER, …
```
> feat(optimizer): match index and plan nested index join

- CMakeLists.txt
- src/include/common/bustub_instance.h
- test/sql/baby_arithmetic.slt
- tools/sqllogictest/parser.cpp
- tools/sqllogictest/parser.h
- tools/sqllogictest/sqllogictest.cpp
Example:
```
query
select 1 + 2;
----
3
query
select 1 + 2 + 3;
----
6
query
select 1 - 2 + 5 - 10;
----
-6
query
select 1 + 2 + 3 + null;
----
integer_null
query
select 1 > 2 and 2 > 3;
----
false
query
select null > 2 and 2 > 3;
----
false
query
select null < 2 and 2 < 3;
----
boolean_null
query
select null > 2 or 2 > 3;
----
boolean_null
query
select null < 2 or 2 < 3;
----
true
statement ok
select colA + colB, colA, colB, colA - colB from __mock_table_1;
```
close https://github.com/cmu-db/bustub/issues/343
> feat(sqllogictest): support query statements

- src/include/storage/index/index.h
Signed-off-by: El-even-11 <zhao_ziqian@sjtu.edu.cn>
Remove incorrect unused tag from `InsertEntry()` comments.
> fix(typo): remove incorrect unused tag

- src/include/concurrency/lock_manager.h
The original starter code is implying that students can hold a reference to the unordered_map, which is wrong and might cause race condition.
> fix(p4): potential race in lock manager

- src/include/execution/executors/aggregation_executor.h
- src/include/execution/executors/delete_executor.h
> fix(typo): modify incorrect description

- build_support/run_clang_tidy.py
Enables colored error message for clang tidy (used in `make check-clang-tidy-p0`).
- Uses code modified from Django GitHub [repo](https://github.com/django/django/blob/main/django/core/management/color.py) to check if output supports coloring.
> enable color in clang tidy

- src/include/storage/page/page.h
so that ASAN can detect page overflow (which is rather hard to debug in B+ tree project -- students will find their page pin count magically turned into 0)
> chore: use ptr for page

- src/include/common/logger.h
The ` #if `  command only finds the macro definition. If it is not found, it defaults to 0. But ` LOG_LEVEL ` is a C++'s constexpr variable which the compiler will process after the ` #if ` command. So what ever the LOG_LEVEL is , the logger will print all log.
If you still want to use constexpr variable , maybe you should use the template technology instead of `#if`.
In my opinion, it is feasible and inexpensive to simply replace it with a macro definition.
Finally, a new function suggests that for concurrent programs, the log should carry the thread id, and users can simply control the format, log level filtering, or users prefer streaming output log, and so on. If you need, I can provide header-only one.
> fix(logging): LOG_LEVEL doesn't work

- src/common/bustub_instance.cpp
- tools/wasm-shell/extra_files/index.html
- tools/wasm-shell/wasm-shell.cpp
This PR removes background thread from lock manager, so that we can use the shell in web browser.
> fix(web-shell): lock manager fix

- src/execution/init_check_executor.cpp
- src/include/execution/executors/init_check_executor.h
Otherwise the pointer is destructed after making the executor...
> fix: store the pointer in init_check

- test/concurrency/deadlock_detection_test.cpp
- tools/terrier_bench/terrier.cpp
Otherwise all rows will be locked and it's hard to optimize.
> chore: sleep verify thread in release mode

- src/execution/aggregation_executor.cpp
- src/include/execution/executors/aggregation_executor.h
In the AggregationExecutor class, rename child to child_executor for better consistency with the comments and other executors.
> style: rename child -> child_executor to keep consistency

- test/concurrency/common_checker.h
This PR introduces overloaded versions of the `Insert()` and `Delete()` functions in `common_checker.h`
The original versions of these functions were specifically tailored to comply with the Gradescope tests, which made them somewhat inflexible. 
To enhance usability, the newly added overloaded versions support a broader range of input formats.
The main objective of these additions is to facilitate students in writing their own test cases. 
It will allow them to thoroughly test their implementation locally, providing a more flexible and user-friendly testing environment.
This update does not impact the original functions, ensuring continued compatibility with Gradescope tests.
> feat: Add overloaded version for Insert() & Delete() in common_checker.h

- src/include/catalog/catalog.h
- src/include/planner/planner.h
- src/include/storage/table/table_heap.h
- src/storage/table/table_heap.cpp
To mention, the private ctor will initialize the underlying `bpm_` to `nullptr`, and left the `page_id` to be `INVALID_PAGE_ID`
> feat: Add a private ctor in TableHeap to avoid nullptr table when running binder tests

- src/common/bustub_instance.cpp
- src/include/common/bustub_instance.h
This PR resolves the corresponding `todo`, and since `recovery test` is currently disabled, it's okay to change from raw pointer to unique pointer.
> feat(todo): change raw pointer to unique pointer for member variables in bustub_instance.h

- test/buffer/buffer_pool_manager_test.cpp
This PR solves #585 by changing the instantiation of `std::uniform_int_distribution` from the implicit `char` to the explicit `int`, which makes the `static_assert` in `MacOSX13.3.sdk` happy. (Detailed reason is mentioned in the issue)
Also improve the overall format for this test🥰
> fix(test): ensure compatibility std::uniform_int_distribution for binary data generation & improve overall format

- src/include/storage/page/b_plus_tree_header_page.h
- src/include/storage/page/b_plus_tree_internal_page.h
- src/include/storage/page/b_plus_tree_leaf_page.h
- src/include/storage/page/b_plus_tree_page.h
- src/storage/index/b_plus_tree.cpp
> chore(docs): revise docs related to B Plus Tree

- src/include/storage/disk/disk_scheduler.h
- test/storage/disk_scheduler_test.cpp
after a second thought it would be a better idea to pass the promise with ownership
> p1: use owned promise for disk scheduler

- src/include/storage/page/extendible_htable_bucket_page.h
- src/include/storage/page/extendible_htable_directory_page.h
- src/include/storage/page/extendible_htable_header_page.h
- src/include/storage/page/hash_table_page_defs.h
- src/storage/page/CMakeLists.txt
**Page Layout**
```cpp
/**
* Header page format:
*  ---------------------------------------------------
* | DirectoryPageIds(2048) | MaxSize (4) | Free(2044)
*  ---------------------------------------------------
* 
* Directory page format:
*  --------------------------------------------------------------------------------------
* | MaxSize (4) | GlobalDepth (4) | LocalDepths (512) | BucketPageIds(2048) | Free(1528)
*  --------------------------------------------------------------------------------------
*
*
* Bucket page format:
*  ----------------------------------------------------------------------------
* | METADATA | KEY(1) …
```
> feat: define new extendible hash table pages specification

- src/storage/page/extendible_htable_page_utils.cpp
Change `curr_ld` to `curr_count` so students could have matching debug log info.
> fix: display correct debug info for pointer count verification

- CMakeLists.txt
- src/execution/CMakeLists.txt
- src/execution/topn_per_group_executor.cpp
- src/include/execution/executors/topn_per_group_executor.h
- src/include/execution/plans/abstract_plan.h
- src/include/execution/plans/topn_per_group_plan.h
> add topn_per_group plan and executors for leaderboard task

- src/common/bustub_instance.cpp
- test/sql/p3.leaderboard-q1-window.slt
> p3: check commit success and explain full q1

- src/common/bustub_instance.cpp
- src/include/common/bustub_instance.h
- src/include/concurrency/transaction.h
- test/CMakeLists.txt
- test/txn/txn_common.h
- test/txn/txn_index_concurrent_test.cpp
- test/txn/txn_index_test.cpp
- tools/terrier_bench/terrier.cpp
* enlarge BPM size for p4, no eviction for terrier benchmark to avoid contention on BPM
* colorize test output to make it easier to read
* misc format fixes and redirect output to stderr
> p4: misc fixes for tests

- test/storage/disk_scheduler_test.cpp
array used as a parameter decays to the address of its first element. No need to reinterpret cast it.
> p1: tiny fix of array usage in a test

- README.md
> add paragraph on autograder from the course website + warn on gradescope ban

- src/type/value.cpp
backport from https://github.com/skyzh/bustub-vectordb/pull/1 @UnpureRationalist
---
Hi there,
Thanks for your excellent tutotial for vector database beginners. When I follow your tutorial and test my implementions using the commands [here](https://skyzh.github.io/write-you-a-vector-db/cpp-02-setup.html#testing), memory leak was reported by AddressSanitizer.
After debugging, I found the destructor of class `Value` was not implemented well for `VECTOR` type. So this PR fixed the bug by modifying destructor along with the copy constructor (The copy assignment operator do not need to change since it is pass by  value).
After fixing the bug, the test can passed correctly without memory leak.
> fix memory leak of vector type

- src/include/storage/page/extendible_htable_directory_page.h
- src/include/storage/page/extendible_htable_header_page.h
- tools/htable_bench/htable_bench.cpp
> Spring 24: Modifications for P2

- src/include/execution/plans/index_scan_plan.h
- test/sql/p3.05-index-scan.slt
Updates index plan node and adds sqllogictests to be consistent with the new project specs.
> Spring 2024: P3 Index Changes

- CMakeLists.txt
The include dir path of the third-party library backward-cpp is set incorrectly. It should be `${PROJECT_SOURCE_DIR}/third_party/backward-cpp` rather than `${PROJECT_SOURCE_DIR}/third_party/backward-cpp/include`
if I want to use backward-cpp in the src directory, for example, include "backward.hpp" in the src/storage/page/extendible_htable_bucket_page.cpp, it will cause a compilation error: `fatal error: backward.hpp: No such file or directory`
> fix third_party backward-cpp include dir path

- src/include/storage/table/tuple.h
- src/storage/table/tuple.cpp
fix #699 
`Tuple::KeyFromTuple` doesn't  modify any members and call any non const methods. So it should be defined as a const class methods.
> change non const `Tuple::KeyFromTuple` to const method #699

- src/include/storage/disk/disk_manager.h
- test/buffer/buffer_pool_manager_test.cpp
- test/container/disk/hash/hash_table_page_test.cpp
- test/container/disk/hash/hash_table_test.cpp
- test/recovery/recovery_test.cpp.disabled
- test/storage/disk_manager_test.cpp
- test/table/tuple_test.cpp
> Adding log file name getter in disk manager + other changes

- CMakeLists.txt
- src/include/primer/hyperloglog.h
- src/include/primer/hyperloglog_presto.h
- src/primer/CMakeLists.txt
- src/primer/hyperloglog.cpp
- src/primer/hyperloglog_presto.cpp
- test/primer/hyperloglog_test.cpp
> P0 Starter Code

- src/buffer/lru_k_replacer.cpp
- src/include/buffer/lru_k_replacer.h
- test/buffer/lru_k_replacer_test.cpp
This PR changes the signature of the `Evict` method on the LRU-K replacer to use a `std::optional` return type containing the frame instead of writing it into a pointer.
> change LRU-K `Evict()` signature

- test/buffer/buffer_pool_manager_test.cpp
This test adds a deadlock test into the public project 1 tests.
We need to add this otherwise students may run into problems in future projects.
> Add a Project #1 Deadlock Test

- src/include/buffer/buffer_pool_manager.h
Adds a better hint for ways to implement helper functions.
> add a better hint to bpm header

- src/buffer/buffer_pool_manager.cpp
Small change, use the `fmt::println` function instead of the unwieldy `std::cerr << ...`. Also shows students that this is available to them.
> Use fmt::println instead of std::cerr

- test/buffer/buffer_pool_manager_test.cpp
This test checks if an implementation has a pin count / evictability mismatch bug.
> Add `EvictableTest`

- test/buffer/buffer_pool_manager_test.cpp
This test ensure that people actually use frame latches, because it is possible to pass a lot of the tests if you completely disregard locking.
> Add new frame latching test

- src/execution/mock_scan_executor.cpp
Add new mock tables for fall 2024. Introduce mock tables for testing external merge sort.
> feat(f24-p3): add new mock tables

- src/include/storage/disk/disk_manager.h
- src/include/storage/disk/disk_manager_memory.h
- src/include/storage/disk/disk_scheduler.h
- src/storage/disk/disk_manager.cpp
- tools/sqllogictest/sqllogictest.cpp
This PR introduces necessary test utils for checking students' external merge sort implementations, including:
1. Maximum number of pages written to disk
2. Minimum number of pages written to disk
3. Minimum number of pages deleted on disk
> test(sqllogictest): add test utils regarding bpm & disk

- src/include/primer/hyperloglog.h
Fix typo in AddElem documentation: change 'Ddds' to 'Adds'
> Fix typo in AddElem documentation: change 'Ddds' to 'Adds'

- test/storage/b_plus_tree_delete_test.cpp
Add the test for the case where the only node in B+Tree is deleted. The original tests do not handle this scenario, and if students fail to handle this properly, their P3 will be affected.
> add(p2): test for deleting the only remaining node

- test/txn/txn_index_concurrent_test.cpp
The original error message is a bit misleading. One student came to my OH with his data_writer being empty. But the error message still said "more than one row fetched". It took me a while to figure it out...
> fix(f24 p4): misleading error

- .github/workflows/cmake.yml
- build_support/packages.sh
- third_party/argparse/.github/workflows/ci.yml
MacOS 12 CI is deprecated. Remove it for unnecessary failures.
> remove MacOS 12 (Monterey) CI

- src/include/storage/disk/disk_manager.h
- src/include/storage/disk/disk_manager_memory.h
- src/include/storage/disk/disk_scheduler.h
- src/storage/disk/disk_manager.cpp
- src/storage/disk/disk_manager_memory.cpp
- test/storage/disk_manager_test.cpp
> feat: make disk manager actually reclaim disk space on delete

- test/buffer/buffer_pool_manager_test.cpp
- test/storage/page_guard_test.cpp
Update tests for P1. See private PR for details.
> P1 updates

- src/buffer/buffer_pool_manager.cpp
- src/include/buffer/buffer_pool_manager.h
- src/include/storage/page/page_guard.h
- src/storage/page/page_guard.cpp
Change buffer pool manager flush API to be more understandable:
1. Added flush methods on read and write page guards that will always flush a consistent state to disk (due to the guard locking the page).
2. Added safe and unsafe flush methods to the buffer pool manager that lock the pages and don't respectively. The unsafe ones will be faster due to not having to lock pages, but they may flush an inconsistent state to disk if the page is modified while it is flushed. Note that previously, the buffer pool manager only had unsafe flush methods.
> p1 (bpm) flush api changes

- src/buffer/buffer_pool_manager.cpp
Remove note saying to use `DiskScheduler::IncreaseDiskSpace`, as disk space is maintained internally by the disk manager now.
> Fix p1 (bpm) new page documentation

- src/include/storage/index/index_iterator.h
- src/include/storage/page/b_plus_tree_internal_page.h
- src/include/storage/page/b_plus_tree_leaf_page.h
- src/include/storage/page/b_plus_tree_page.h
- src/storage/index/b_plus_tree.cpp
- src/storage/index/index_iterator.cpp
- src/storage/page/b_plus_tree_internal_page.cpp
- src/storage/page/b_plus_tree_leaf_page.cpp
- src/storage/page/b_plus_tree_page.cpp
Added some comments and stub functions. The contention test will be fixed in another PR.
> p2 (Database Index : B+-Tree)

- src/buffer/buffer_pool_manager.cpp
- src/include/storage/disk/disk_scheduler.h
The disk manager now keeps track of deallocated pages and uses the space for new pages, so update the comments for buffer pool manager to reflect that. This should also help students in project 3 where deallocating is necessary.
> Update comments relating to DeallocatePage

- src/include/concurrency/transaction.h
- tools/terrier_bench/terrier.cpp
p4 fixes for leaderboard tests:
- Adds txn commit to PrintPlan() in terrier.cpp. Before, the watermark would get stuck due to the uncommitted transaction, making garbage collection much harder.
- Changes ClearUndoLogs in transaction.h to clear vector undo_logs_ and return void
> Fixes p4 bugs

- src/include/common/util/hash_util.h
https://github.com/polyominal/bustub/blob/9988c8503cc3e5107cc750c651ebeaef2efe8ce6/src/include/common/util/hash_util.h#L32-L39
The hash function uses raw `bytes[i]` in `char`. This creates a subtle bug. C++ doesn't define whether `char` is signed or unsigned.
For byte values over 127, this matters:
- Signed platforms: values become negative (the expected behavior)
- Unsigned platforms: values stay positive (0-255)
This bit me during [HyperLogLog project](https://15445.courses.cs.cmu.edu/fall2024/project0/):
https://github.com/polyominal/bustub/blob/9988c8503cc3e5107cc750c651ebeaef2efe8ce6/test/primer/hyperloglog_test.cpp#L58-L108
My code failed on my machine (unsigned `char`) but passed elsewhere (signed `char`).
Proposed fix: Cast to `int8_t` for consistent behavior.
```cpp
hash = ((hash …
```
> fix: make HashUtil::HashBytes more platform independent

- .clang-tidy
- src/binder/fmt_impl.cpp
- src/catalog/table_generator.cpp
- src/include/catalog/catalog.h
Fixing bugs introduced when adding support for Ubuntu 24.0.4
Remove `bugprone-unchecked-optional-access` check from clang-tidy
> clang-tidy update + small fixes
